// src/components/ui/button.tsx
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import * as React from "react";

import { cn } from "@/lib/utils";

const buttonVariants = cva(
  "inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 rounded-md text-sm font-medium whitespace-nowrap transition-all outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default:
          "bg-primary text-primary-foreground shadow-xs hover:bg-primary/90",
        destructive:
          "bg-destructive text-white shadow-xs hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:bg-destructive/60 dark:focus-visible:ring-destructive/40",
        outline:
          "border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:border-input dark:bg-input/30 dark:hover:bg-input/50",
        secondary:
          "bg-secondary text-secondary-foreground shadow-xs hover:bg-secondary/80",
        ghost:
          "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2 has-[>svg]:px-3",
        sm: "h-8 gap-1.5 rounded-md px-3 has-[>svg]:px-2.5",
        lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
        icon: "size-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);

function Button({
  className,
  variant,
  size,
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean;
  }) {
  const Comp = asChild ? Slot : "button";

  return (
    <Comp
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  );
}

export { Button, buttonVariants };

// src/lib/components/Button.svelte
<script lang="ts">
	import { Button } from 'bits-ui';
	import type { Snippet } from 'svelte';
	import { cn } from '$lib/utils';
	import { cva, type VariantProps } from 'class-variance-authority';
	import type { HTMLButtonAttributes } from 'svelte/elements';

	const variants = cva(
		'inline-flex min-w-32 disabled:cursor-not-allowed cursor-pointer items-center justify-center gap-2 rounded-lg px-4 py-2 duration-300',
		{
			variants: {
				variant: {
					primary:
						'bg-[var(--teal-5)] text-[var(--teal-12)] hover:bg-[var(--teal-4)] disabled:bg-[var(--gray-4)] disabled:text-[var(--gray-11)]',
					secondary:
						'bg-[var(--teal-3)] text-[var(--teal-11)] hover:bg-[var(--teal-4)] disabled:bg-[var(--teal-4)]',
					outlined:
						'border border-[var(--teal-6)] bg-[var(--teal-2)] text-[var(--teal-12)] hover:bg-[var(--teal-3)] disabled:text-[var(--teal-11)] disabled:bg-[var(--teal-3)]',
				},
			},
			defaultVariants: {
				variant: 'primary',
			},
		}
	);

	type Props = {
		children: Snippet;
		variant?: VariantProps<typeof variants>['variant'];
	} & HTMLButtonAttributes;
	const { children, variant, ...others }: Props = $props();
</script>

<Button.Root class={cn(variants({ variant }))} {...others}>{@render children()}</Button.Root>
